### ISSUE TITLE
[Feature]: Deploy SPAship Manager via Operator

### ISSUE THREAD

**Issue by lkrzyzanek** [spaship/spaship#1169]
## Is your feature request related to a problem? Please describe:

To simplifier the SPAship Manager UI deployment let's use Operator for it.

## Describe the solution you'd like:

The manager consist of 2 things: config (under /config/manager.js) and the Manager SPA.

### Step 1: The manager build needs to be pushed to branch ideally separate repo.

Example: repo `spaship-build` with subdirectory `manager` containing the latest build (by Github action) and tag is the same as SPAship version. See how to use Github Action in [spaship-examples](https://github.com/spaship/spaship-examples/blob/main/.github/workflows/publish.yaml#L21)

In future we could use this repo for other SPAs.

### Step 2: Deployment spec 
The Manager configuration is deployment specific thing so it should be not part of build.

The deployment git would contains `website.yaml` in `main` branch and in `manager-config`  dir will be manager.js config.
The `website.yaml`:
```yaml
apiVersion: v1

envs:
  dev:
    branch: main
  prod:

components:
  - context: /config
    kind: git
    spec:
      dir: /manager-config
      envs:
        prod: 1.0.0 # or use directly main
  - context: /
    kind: git
    spec:
      url: https://github.com/spaship/spaship-build.git
      dir: /manager
      envs:
        prod: 1.0.0
```

### Step 3: Deploy via Operator
Create deployment.yaml descriptor:
```yaml
apiVersion: spaship.io/v1
kind: Website
metadata:
  name: manager
spec:
  gitUrl: <GIT URL from step 2>
  secretToken: <TOKEN>
  previews: true
  displayName: SPAship Manager
```
and deploy to cluster:
```shell
kubectl create namespace spaship-manager
kubectl apply -n spaship-manager-f deployment.yaml
```
Optionally register webhook in both git repositories.
