### ISSUE TITLE
[Feature]: Add an option to chose compression for assets

### ISSUE THREAD

**Issue by gautamkrishnar** [spaship/spaship#1514]
## Is your feature request related to a problem? Please describe:
Currently, spaship serves assets uncompressed, it doesn't provide any option to set the compression needed by the SPAs. Compression can improve SPA's first paint time drastically without making many changes in the code.

## Describe the solution you'd like:
Add a new key to the spaship.yml file named `compression` eg:
```yml
name: rhc-certification-workflow
path: /projects
single: true
buildDir: build
compression: brotli
```
The above key supports two values: `brotli`, `gzip` (more values can be added if required)

Lets say the user provided the value as `brotli`, the spaship router will serve the SPA enabling the Brotli compression,

## Describe alternatives you've considered:
None

## Additional context:
- https://tech.oyorooms.com/how-brotli-compression-gave-us-37-latency-improvement-14d41e50fee4?gi=6ee9c6a4cf8e
