### ISSUE TITLE
[Feature]: Add support to multiple paths in spaship.yaml

### ISSUE THREAD

**Issue by gautamkrishnar** [spaship/spaship#2439]
## Is your feature request related to a problem? Please describe:
Having multiple paths in spaship.yaml will allow users to deploy a single spa to multiple paths if they need. 

## Describe the solution you'd like:
Current spaship.yaml only supports single  path, example:
```yaml
name: rhc-product-listings
path: /manage
single: true
buildDir: build
```

This can be enhanced to support an array of paths as well:
```yaml
name: rhc-product-listings
path: 
    - /manage
    - /example1
    - /example2
single: true
buildDir: build
```

## Describe alternatives you've considered:
We can deploy spaship to multiple paths using spaship cli's command line args but this involves running CLI mulple times for each path.

## Additional context:
n/a
