### ISSUE TITLE
[Feature]: Spaship deploy Github Action

### ISSUE THREAD

**Issue by gautamkrishnar** [spaship/spaship#756]
## Is your feature request related to a problem? Please describe:
Spaship Github action allows the users of [Github actions](https://github.com/features/actions) to integrate Spaship into their Github CI/CD pipeline easily.

## Describe the solution you'd like:
1. Create a repository at https://github.com/spaship/spaship-deploy that contains source code for the action.
2. Spaship deploy action supports these parameters: `deploy_env`, `dev_url`, `dev_key`, `qa_url`, `qa_key`, `stage_url`, `stage_key`, `prod_url`, `prod_key`, `name`, `path`, `single` and `builddir`. These paremeters can be given as repo secrets or vis spaship.yaml file.
3. Action contains a wrapper a spaship cli and its core job of it is to deploy the app to the corresponding environments when triggered.
#### Advantages

- Users can use the Spaship deploy action in their CI/CD pipeline to make the deployments easier. For example, they just need to add a file like the one below to .github/workflows/build-and-deploy.yml file to use the action:

```yml
name: Build and deploy to dev environment
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy-dev:
    name: Generate build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - uses: spaship/spaship-deploy
          with:
              deploy_env: dev
```

- Similarly, they can use `workflow_dispatch` to trigger the manual deployments, example:
```yml
name: Build and deploy to any environment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment'
        required: true
jobs:
  build-and-deploy-dev:
    name: Generate build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - uses: spaship/spaship-deploy
          with:
              deploy_env: ${{ github.event.inputs.environment }}
```
This will allows users to deploy to their environment of choice from a particular branch via the GitHub actions web interface. It will look like:
<img src="https://user-images.githubusercontent.com/8397274/91702313-2e24b200-eb96-11ea-99b8-0cece59ee80c.png" width="400px">

I will be happy to take this up, what do you guys think about this.
