### ISSUE TITLE
add an ownership field to spaship.yaml

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#76]
Each SPA should have a configuration field for who owns it.  It could be an email address for an individual or a team mailing list.

Need to decide what to name it.  I'm thinking `owner` but I'm very open to other ideas.

Here's a mocked up example:

```yaml
name: My SPA
path: /my/spa
owner: my-spa-dev@domain.com
```

**Comment by mwcz** [comment]
Perhaps `email` would be a better field name.

**Comment by sayak-sarkar** [comment]
How about 
```
author:
  - name: John Doe
    email: john@doe.com
````

**Comment by mwcz** [comment]
That would work.  I would like it if we could keep the yaml file "flat", no nested properties, purely for simplicity.  Yaml handles nested properties just fine, but I love the simplicity of a flat file.  It's a minor preference, but it would be nice.

**Comment by mwcz** [comment]
Thinking about this now, I think the property should be `contact`, and would usually be set to the dev mailing list for each app.

**Comment by mwcz** [comment]
I double-checked yaml syntax and the `-` shouldn't be needed.  This looks simple enough:

```yaml
name: My SPA
path: /my/spa
contact:
  name: John Doe
  email: my-spa-dev@domain.com
```

I'm totally fine with nested properties in this form.
