### ISSUE TITLE
[Feature]: Removed API url path before use it

### ISSUE THREAD

**Issue by kunyan** [spaship/spaship#878]
## Is your feature request related to a problem? Please describe:

Someone might be use the api versioning url into .spashiprc file

```yaml
envs:
  dev:
    url: https://spaship-api-cpops-catalog-dev.ext.us-east.aws.preprod.paas.redhat.com/api/v1
    apikey: xxxx
```

But it will got following error

![Screen Shot 2020-10-30 at 11 32 48 AM](https://user-images.githubusercontent.com/752130/97657147-1a1d0400-1aa4-11eb-8eef-b41c4e336934.png)

## Describe the solution you'd like:

We can just get the host name of `api` before we use it
