### ISSUE TITLE
[Bug]: User upload a name with `/` spa will broken manager

### ISSUE THREAD

**Issue by kunyan** [spaship/spaship#889]
## Describe the bug:

Nilam is working on test spa on access.
And he did a mistake to write a yaml file like this

```yaml
# SPAship config file
# generated by @spaship/common.config v0.11.0

name: /labs-teamroster
path: /labs-teamroster
single: true
ref: 0.1.0
```

He upload this spa via manager. with the correct name `labs-teamroster`.

I checked the database and www storage, all name are `labs-teamroster`.
But it show `/labs-teamroster` in the manager, makes the application index can not open

<img width="978" alt="Screen Shot 2020-11-04 at 8 09 51 PM" src="https://user-images.githubusercontent.com/752130/98110223-bba7b980-1ed9-11eb-85de-a0e2bbdda91a.png">
<img width="468" alt="Screen Shot 2020-11-04 at 8 10 47 PM" src="https://user-images.githubusercontent.com/752130/98110298-db3ee200-1ed9-11eb-84b3-44c66ee62d5d.png">

It broke the UI router.

I think there are 2 plans

1. Make the manager could handle the name with `/` (Using url encode)
2. Prevent user using url code in the name

@mwcz @sayak-sarkar what do you think ?

## Environment;

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)
